// <auto-generated />
namespace DataBaseClasses.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _1602 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_1602));
        
        string IMigrationMetadata.Id
        {
            get { return "202402160354199_1602"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
