// <auto-generated />
namespace МИС__ГКБ_Большие_Кабаны_.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _0502 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_0502));
        
        string IMigrationMetadata.Id
        {
            get { return "202402050617434_0502"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
