// <auto-generated />
namespace МИС__ГКБ_Большие_Кабаны_.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class gospitalizacia : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(gospitalizacia));
        
        string IMigrationMetadata.Id
        {
            get { return "202402060721161_gospitalizacia"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
